apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  selector:
    app: ticket-service
  ports:
    - port: 3004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service
          image: services-ticket-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3004
          envFrom:
            - configMapRef:
                name: global-config
            - secretRef:
                name: global-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
