apiVersion: v1
kind: Secret
metadata:
  name: global-secret
type: Opaque
data:
  ACCESS_TOKEN_SECRET_SIGNATURE: "NzMzMjY5M2U0ZDVkMGIwZmI0N2YwZjM3MWU1ZDU5ZDIwM2QwZTc1ZWUxYzQ2ZDA2NjI2ODBmZjhiMzFiNTdlOWRiNDMyZWEwODY4M2E3Y2JlYzU4OWQzMjMxMWMxN2Q2NDhmOWIwZmI5MTVmZjJiYjRlM2ZkOGMwMmFkZmM5NDIyYTAzMzFhNzA5ODY5MDFiNGRhNWU1MDhiZDRjZDUxOTI0M2NjZTIwNTJkZDA1OWVjOTVmZjIxMzg5NzFkM2FjYWI4ZTlkOGU5ZDYxYTAwN2QyNTEyMzg3YzUyYWViMjBkMWNhZWU3ODZhNjhkODE2YmFlZWE3MzY4MTIyN2QyZA=="
  REFRESH_TOKEN_SECRET_SIGNATURE: "M2Y5MTc4NDFkODQ2YzdmMDBiMWZkMDk4MjExNDJmN2M4MDJmZTUwMDdhZjQxNzI4MDJiN2Y1YTI2MDFiNjIzNzUwNzk5OTZhN2I2OTY0Y2E1NjZmNzk0MzYzNjg2NDEyYTBjNWU1OTM4OTBiZjY3MTg3MDU5NTBiMWQ3ODFjMTMxZTFjZjFlNTFjNDFlZGQ4ZDJiOTRlZWNiZmJlMGJlNDlkODJiOGEwNjkxYTY4OTMxZmY2ODhkNTkyYmUyZDFhYWUxYWVkZmEyMWFkNGVlNDEwM2I1YTkzMGViYmYxZDA5NjUxZjQ5OGU0ZGM4NmMyNDhkMGEzYTIzNzhhZDM0MQ=="
  CLOUDINARY_NAME: "bWluaGFuaDU1Mw=="
  CLOUDINARY_KEY: "MzQ1OTY2ODE4NjQ4NDI0"
  CLOUDINARY_SECRET: "bC1ZWGdVMmR3aWxXcWxQbEVEZTFhN3IwaDhZ"
  MONGODB_URI: "bW9uZ29kYitzcnY6Ly9odXluaG1pbmhhbmg1NTM6RTk3VVMyWFl5OWhIMVNXT0BtaW5oYW5oNTUzLm1jZmd4eGYubW9uZ29kYi5uZXQvTFZUTg=="
  PAYOS_CLIENT_ID: "YzRhY2RmZmYtMjI4ZS00OGY3LTllZWItNGNhMzMyMmM4NTRl"
  PAYOS_API_KEY: "NTEwYmE3NTItMjdlZS00OWZiLTkxYjQtMDk3YWUxMGZiN2Zk"
  PAYOS_CHECKSUM_KEY: "ZmRiMmMwY2FjYzFmOTk3YTAwMDYwMzJiZmU5NDY2M2I0YzRkZTExMDQ0ZmQ1MzMzZmMxMDA5MWVhMGIzMDY1NA=="
  EMAIL_USER: "bWluaGFuaHZwbkBnbWFpbC5jb20="
  EMAIL_PASS: "bGVmcnFicGJ5cnJ0aGVtaA=="
